version: '3'

services:
  go: &go
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - shigoto

networks:
  shigoto:
    external:
      name: shigoto_network
